---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure1/Figure1.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/244977/articles/324013/master/file/figures/Figure1/Figure1.svg"
